name: idea_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  in_app_purchase: ^3.1.7
  flutter_scatter:
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5
  bubbles_selection: ^0.0.1-dev.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
