// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQf-ZkeEohOXdyE6W5mJxpitPWt4Wj17c',
    appId: '1:217786530262:android:c27ddcf90ccf097c2b8c77',
    messagingSenderId: '217786530262',
    projectId: 'idea-demo-71ee9',
    storageBucket: 'idea-demo-71ee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVg293FdYDE6WP6d4sY0i9dKOpxcuT84',
    appId: '1:217786530262:ios:317ac950278251af2b8c77',
    messagingSenderId: '217786530262',
    projectId: 'idea-demo-71ee9',
    storageBucket: 'idea-demo-71ee9.appspot.com',
    iosClientId:
        '217786530262-u7349j50ueqbm7mcpkdlitp02i0fnm81.apps.googleusercontent.com',
    iosBundleId: 'io.ideatestproject.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmVg293FdYDE6WP6d4sY0i9dKOpxcuT84',
    appId: '1:217786530262:ios:560435f7a22cde8b2b8c77',
    messagingSenderId: '217786530262',
    projectId: 'idea-demo-71ee9',
    storageBucket: 'idea-demo-71ee9.appspot.com',
    iosClientId:
        '217786530262-cia3gr8r73gla9uhtsq55mfaq91bnmur.apps.googleusercontent.com',
    iosBundleId: 'com.example.ideaApp',
  );
}
